version: "3.8"

services:
  yii2-app:
    container_name: yii2-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - yii2-db
    environment:
      DB_HOST: yii2-db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASS: root

  yii2-db:
    container_name: yii2-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
