services:
  yii2-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:80"
    env_file: .env
    depends_on:
      - yii2-db
    volumes:
      - ./:/var/www/html

  yii2-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-yii2advanced}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    depends_on: [yii2-db]
    ports:
      - "${ADMINER_PORT:-8081}:8080"

volumes:
  mysql_data:
